version: '3.9'

services:

  db:
    image: postgres:16.8
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: pomodoro

  cache:
    image: redis:7.4.2-alpine
    restart: always
    ports:
      - '6379:6379'